name: Java CI with Maven

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK 11  # Change Java version to 11 or any version >=9
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'  # Change this from 8 to 11 or a newer version

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      working-directory: flash-card  # Set working directory to where pom.xml is located
      run: mvn clean install

    - name: Run tests
      working-directory: flash-card  # Ensure tests run from the correct directory
      run: mvn test
